name: Convert slides

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: nbconvert .ipynb's
      uses: runsascoded/nbconvert@v1.2
      with:
        args: -f -x -o slides